export const FOCUS = 'header/focus'
export const BLUR = 'header/blur'
export const MOUSE_ENTER = 'header/mouseEnter'
export const MOUSE_LEAVE = 'header/mouseLeave'
export const CHANGE_LIST = 'header/changeList'
export const LIST_SWITCH = 'header/listSwitch'
